### ISSUE TITLE
Incorrect description on the last calculatePayroll test

### ISSUE THREAD

**Issue by Leepzig** [learn-co-curriculum/js-advanced-functions-introduction-to-context-lab#17]
The test says `it("correctly sums the payroll burden to $11,880 when passed an array of employee records"`

But the last statement is:

`expect(calculatePayroll(employeeRecords)).to.eql(12480)`

**Comment by graciemcguire** [comment]
Hey @Leepzig , we have changed the test description. Thanks for flagging!
