### ISSUE TITLE
Typos on README.md

### ISSUE THREAD

**Issue by levimllr** [learn-co-curriculum/js-advanced-functions-introduction-to-context-lab#3]
The descriptions of the createTimeInEvent and createTimeOutEvent functions state that "A date stamp ("YYYY-MM-DD")" is provided as an argument. The date stamp string passed in by the test is of the form "YYYY-MM-DD hhhh".

"findEmployeebyFirstName" is not in camelCase, which will lead to some confusion with students who are being trained to name variables and functions in camelCase.

**Comment by sgharms** [comment]
1. Updated README to provide date + stamp (`createTimeOutEvent`, `createTimeInEvent`)
2. Updated `findEmployeebyFirstName` to conform to camelCase
