### ISSUE TITLE
Duplicative functions listed in instructions

### ISSUE THREAD

**Issue by keepitmovingforward** [learn-co-curriculum/js-advanced-functions-introduction-to-context-lab#5]
**createEmployees**
Argument(s)
Array of Arrays
Returns
Array of Objects
Behavior
Converts each nested Array into an employee record using createEmployeeRecord and accumulates it to a new Array

**createEmployeeRecords**
Argument(s)
Array of Arrays
Returns
Array of Objects
Behavior
Converts each nested Array into an employee record using createEmployeeRecord and accumulates it to a new Array

**Comment by keepitmovingforward** [comment]
the findEmployeeByFirstName function is relying on createEmployeeRecords function in Tests but this should be pointed to the createEmployees function since they are identical.

**Comment by sgharms** [comment]
Seems I may have gotten my copy and pastes between this readme https://github.com/learn-co-curriculum/js-advanced-functions-context-lab/issues/3 and this lab bungled. Willfix.

**Comment by sgharms** [comment]
OK, this should be fixed now! Thanks.
