### ISSUE TITLE
Tests have wrong date format.

### ISSUE THREAD

**Issue by racheladaw** [learn-co-curriculum/js-advanced-functions-introduction-to-context-lab#8]
The test that says:

describe("hoursWorkedOnDate", function () {
      it("calculates that the employee worked 2 hours", function () {
        cRecord = createEmployeeRecord(["Julius", "Caesar", "General", 1000])
        updatedBpRecord = createTimeInEvent(cRecord, "44-03-15 0900")
        updatedBpRecord = createTimeOutEvent(cRecord, "44-03-15 1100")
        expect(hoursWorkedOnDate(cRecord, "44-03-15")).to.equal(2)
      })
    })

has the wrong date format. The Readme section states that the second argument should have a date format of "YYYY-MM-DD" and that is also the format the Readme says to use for the time in and time out functions.

**Comment by sgharms** [comment]
Good catch. Changed
